### ISSUE TITLE
Support for \NewDocumentEnvironment from xparse

### ISSUE THREAD

**Issue by kiryph** [latex-lsp/texlab#745] opened 2022-08-31 08:05 UTC
texlab raises for
```tex
\documentclass{article}
\usepackage{tabularray} 

\ExplSyntaxOn
\NewDocumentEnvironment{exptblr}{O{}m}
 {
  \use:x
   {
    \exp_not:N \begin{tblr}
    [\exp_not:n{#1}]
    {#2}
   }
 }
 {
  \end{tblr}
 }
\ExplSyntaxOff

\begin{document}

\end{document}
```
following incorrect errors:
```
demo.tex|12 col 4-5 error| Unexpected "}"
demo.tex|13 col 2-3 error| Unexpected "}"
demo.tex|15 col 3 error| Missing "}" inserted
demo.tex|22 col 1 error| Missing "}" inserted
```

Note: As of 2020
- [Providing xparse as part of the [LaTeX] format](https://www.latex-project.org/news/2020/10/01/issue32-of-latex2e-released/#providing-xparse-as-part-of-the-format)
- [LaTeX now contains the L3 programming layer as part of its format](https://www.latex-project.org/news/2020/02/02/issue31-of-latex2e-released/#latex-now-contains-the-l3-programming-layer-as-part-of-its-format)

**Comment by pfoerster** [comment] 2022-09-04 18:36
Thanks for the report. This issue was caused by an error in the LaTeX parser. It should be fixed with 7a84bb992f0268ba17ff891e6d01277fb2aa4a76.

**Closed by pfoerster** 2022-09-04 18:36 UTC
Labels: bug
