### ISSUE TITLE
No compilation error updates in diagnostics unless I restart texlab in Neovim

### ISSUE THREAD

**Issue by Doltonius** [latex-lsp/texlab#679] opened 2022-07-13 14:56 UTC
I am using texlab 4.2.0 with Neovim 0.7.3.
I enabled `texlab.build.onSave` with `latexmk`.
However, the compilation errors do not get updated in the diagnostics after each save (and build), unless I restart the texlab lsp with `:LspRestart<cr>`.

**Comment by Doltonius** [comment] 2022-07-13 15:24
Notice that I did not change the output directory, so I don't think it is a duplicate issue of  #563

**Comment by pfoerster** [comment] 2022-07-16 06:56
Thanks for the report.

> so I don't think it is a duplicate issue of https://github.com/latex-lsp/texlab/issues/563

Yeah, I do not think either. I think this related to the change made in `4.0.0`, which replaced the integrated file watching with LSP file watching. LSP file watching does not seem to be supported for your client so no updates are sent to `texlab`.

I think we need to re-add the server-side file watching, `texlab` generally has a better understanding of the project structure although it still needs a hint in some cases.

**Comment by Doltonius** [comment] 2022-07-25 05:07
When do you plan to re-add server-side file watching? Looking forward.

By the way, if I would like to try out LSP file-watching, what should I do? Use nvim 0.8+?

**Comment by pfoerster** [comment] 2022-07-25 19:24
> By the way, if I would like to try out LSP file-watching, what should I do? Use nvim 0.8+?

It looks like Neovim does not support `workspace/didChangeWatchedFiles` yet.

> When do you plan to re-add server-side file watching? Looking forward.

Can you try out 9a90183b07833852a1eda6caea58c6f583b9bf20, please?

**Comment by Doltonius** [comment] 2022-07-26 04:41
This doesn't seem to be working. In fact, now even after `LspRestart` or a restart of Neovim, the compilation errors still don't show up.

**Comment by pfoerster** [comment] 2022-07-28 16:41
@Doltonius Can you try the master branch again, please? I have made some changes to the file watching.

**Comment by gi1242** [comment] 2022-08-08 00:20
I'm also having various issues now. It's erratic and hard to reproduce, so I can't easily say what the problem is. But I've noticed:
1. If the folder has multiple tex files, then TexlabForward sometimes opens the wrong PDF.
2. I have build.onSave = true; however, sometimes the wrong file is compiled.
3. I often get completion suggestions from a file that's not part of the main document.

I've noticed that these problems go away if I set `build.onSave = false`, and then have a different tool continuously monitor / compile the file. (Problems persisted with latest git version this morning.) I'm using arch, if that matters.

**Comment by anstadnik** [comment] 2022-08-17 04:20
I also experience at least the first two issues, however, for me setting `build.onSave = false` doesn't help.
I experience this [with the following repo](https://github.com/posquit0/Awesome-CV).
First I open resume.tex, compile it, and run `:TexlabForward`. The correct PDF opens.
Then I open in the same nvim instance `cv.tex`. Compile, forward, the correct PDF opens.
Then I go back to `resume.tex`, and try to compile and search forward there, but this time again the `cv.pdf` opens.

**Comment by pfoerster** [comment] 2022-08-17 17:41
> I experience this [with the following repo](https://github.com/posquit0/Awesome-CV).

@anstadnik
Thanks a lot for the example. I was able to reproduce the issue. The local document class in the example folder caused `texlab` to wrongly treat the two separate projects (`resume.tex` and `cv.tex`) as one. This should be fixed with 18db6f5efffcfec3054dcf2c573fdcaff42c697d 👍 .

**Closed** 2022-12-29 19:05 UTC
Labels: bug
