### ISSUE TITLE
Inlay hints in `\include`d files with `auxDirectory`

### ISSUE THREAD

**Issue by jdujava** [latex-lsp/texlab#906] opened 2023-07-24 20:01 UTC
## Setup of auxDirectory

Let's have (for example) the following `aux_dir` for `latexmk`
```perl
# .latexmkrc
$aux_dir = ".aux";
```
and corresponding configuration of `auxDirectory` for `texlab`. Diagnostics are then properly displayed, but the inlay hints are missing in the files which are sourced using `\include`. I will try to explain in the following example.

#### Info about my setup:
- editor: `neovim`
- compilation of latex: `latexmk` via `vimtex` plugin
- setup of texlab: via `nvim-lspconfig`

## Minimal reproducible example

Consider the directory structure
```
.
├── example.tex
└── files
    └── section1.tex
```
where the contents are
```tex
% example.tex
\documentclass[a4paper,12pt]{article}

\usepackage{graphicx}

\begin{document}

\section{Working example}

\begin{figure}[!ht]
    \centering
    \includegraphics[width=1.0\linewidth]{example-image-a}
    \caption{This is an example image.}
    \label{fig:missing}
\end{figure}

\include{files/section1}

\end{document}
```
```tex
% section1.tex
\section{Included section}

\begin{figure}[!ht]
    \centering
    \includegraphics[width=0.3\linewidth]{missing.png}
    \caption{This is a missing image. Leads to a warning/error.}
    \label{fig:random}
\end{figure}
```

## What works and what doesn't

Inlay hint for the first figure is displayed (`example-image-a`), and also warning/error for the second figure (`missing.png`).
However, the inlay hint for the second one is not present. Perhaps surprisingly (at least for me), when the file `section1.tex` is sourced using `\input` instead of `\include`, the inlay hint is displayed.

**Comment by pfoerster** [comment] 2023-07-29 07:56
@jdujava Thanks for the detailed report. This will be fixed with #909.

**Comment by jdujava** [comment] 2023-08-03 21:17
I tried out `texlab v5.8.0` with the following settings passed to LSP via `nvim-lspconfig`
```lua
texlab = {
    build = {
        args = {
            '-pdf',
            '-interaction=nonstopmode',
            '-synctex=1',
            '-outdir=.aux',
            '%f',
        },
        auxDirectory = '.aux',
        logDirectory = '.aux',
    }
}
```
In my experience, the same problem occurs as I described previously (inlay hints work with `\input` but not with `\include`).
@pfoerster Can you reproduce it, or is there anything else I should configure to make it work?

**Comment by pfoerster** [comment] 2023-08-05 06:59
@jdujava Thanks for the update.

> Can you reproduce it

No, I am no longer able to reproduce it with `v5.8.0`. Can you share the contents of all aux files (`example.aux` and `section1.aux`) and where they are located relative to the source files?

Also, you should not set `logDirectory` to `.aux` as the log files are still located next to the TeX  files.

**Comment by jdujava** [comment] 2023-08-05 10:42
@pfoerster Thank you for looking into this!

The initial directory tree is (with the contents given in first comment of this issue)
```
.
├── example.tex
├── files
│   └── section1.tex
└── .latexmkrc
```

Compiling with `latexmk` (version 4.79) either with `vimtex` plugin or directly as
```sh
latexmk -pdf -interaction=nonstopmode -synctex=1 example.tex
```
results in
```
.
├── .aux
│   ├── example.aux
│   ├── example.fdb_latexmk
│   ├── example.fls
│   ├── example.log
│   ├── example.out
│   └── files
│       └── section1.aux
├── example.pdf
├── example.synctex.gz
├── example.tex
├── files
│   └── section1.tex
└── .latexmkrc
```
Since I obtained `example.log` in the `.aux` directory, only after setting `logDirectory` to `.aux` the LSP is able to process it.
I also find this behaviour preferable as it leads to a cleaner directory tree. 

The contents of `*.aux` files are
```tex
% .aux/example.aux
\relax 
\providecommand\hyper@newdestlabel[2]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\global\let\oldnewlabel\newlabel
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\let\newlabel\oldnewlabel
\fi}
\fi}
\global\let\hyper@last\relax 
\gdef\HyperFirstAtBeginDocument#1{#1}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyField@AuxAddToCoFields[2]{}
\@writefile{toc}{\contentsline {section}{\numberline {1}Working example}{1}{section.1}\protected@file@percent }
\@writefile{lof}{\contentsline {figure}{\numberline {1}{\ignorespaces This is an example image.}}{1}{figure.1}\protected@file@percent }
\newlabel{fig:missing}{{1}{1}{This is an example image}{figure.1}{}}
\@input{files/section1.aux}
\gdef \@abspage@last{2}
```
```tex
% .aux/files/section1.aux
\relax 
\providecommand\hyper@newdestlabel[2]{}
\@writefile{toc}{\contentsline {section}{\numberline {2}Included section}{2}{section.2}\protected@file@percent }
\@writefile{lof}{\contentsline {figure}{\numberline {2}{\ignorespaces This is a missing image. Leads to a warning/error.}}{2}{figure.2}\protected@file@percent }
\newlabel{fig:random}{{2}{2}{This is a missing image. Leads to a warning/error}{figure.2}{}}
\@setckpt{files/section1}{
\setcounter{page}{3}
\setcounter{equation}{0}
\setcounter{enumi}{0}
\setcounter{enumii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiv}{0}
\setcounter{footnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{part}{0}
\setcounter{section}{2}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{paragraph}{0}
\setcounter{subparagraph}{0}
\setcounter{figure}{2}
\setcounter{table}{0}
\setcounter{section@level}{1}
\setcounter{Item}{0}
\setcounter{Hfootnote}{0}
\setcounter{bookmark@seq@number}{2}
}
```

**Comment by pfoerster** [comment] 2023-08-05 19:57
@jdujava Thanks! 

The behavior of `latexmk` seems to be a bit strange. Initially I had `section1.aux` right next to `section1.tex`, which is why I was not able to reproduce the issue anymore. However, both cases should be handled by #913 now. Can you give this PR a try, please?

**Comment by jdujava** [comment] 2023-08-05 21:10
I tried out #913 and everything seems to work alright, thanks @pfoerster!

**Closed** 2023-08-06 06:36 UTC
Labels: bug
