### ISSUE TITLE
Pre-filtered completion result failing on lines with `}`

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#510] opened 2021-11-10 14:00 UTC
I have finally managed to find a minimal reproducing example for something that has been bugging me for a long while: Completing `\cite` and `\ref` arguments fails if a) you type to filter the candidates and b) the parser finds a `}` somewhere near.

The following minimal example reproduces this on Neovim:

1. save the following as `texlab.lua`:
<details><summary>config file </summary>

```lua
local minimal_path = vim.fn.stdpath 'cache' .. '/test-minimal-config/site'

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd('set packpath=' .. minimal_path)

_G.load_config = function()
  vim.o.completeopt = 'noinsert,menuone,noselect'
  vim.o.omnifunc = 'v:lua.vim.lsp.omnifunc'
  require('lspconfig').texlab.setup {
    cmd = { vim.fn.stdpath 'data' .. '/lspconfig/texlab' }, -- not needed if texlab is on $PATH
  }
  vim.cmd [[ LspStart ]]
end

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = minimal_path .. '/pack',
      compile_path = minimal_path .. '/pack/_loader/start/_load/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end

local install_path = minimal_path .. '/pack/packer/start/packer.nvim'
if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', '--depth=1', 'git://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config() ]]
```

(Note that depending on where `texlab` is installed, you may need to adapt the `cmd` string; you can omit the line if `texlab` is on the `$PATH`.)

</details>

2. save the following as `test.tex`:

```tex
\documentclass{article}

\begin{document}

\begin{equation}\label{eq:foo}
    1+1=2
\end{equation}

Equation \eqref{eq is a \emph{useful} identity.

\end{document}
```

3. run `nvim --clean -u texlab.lua test.tex`

4. put the cursor after `{eq` and press `<c-x><c-o>` (control-x, followed by control-o)

This should offer `eq:foo` as completion candidate, but nothing happens. If I either
1. remove `eq` and put the cursor after `{`, or
2. remove the rest of the line (in particular the `\emph{useful}`!),

completion works as expected. (On the other hand, the `}` does not have to be on the same line; it can be on a line further down.)

I suspect that the parser is too "greedy" and considers everything to the next closing brace as the prefilter text, instead of only to (e.g.) the first whitespace character.

**Comment by pfoerster** [comment] 2021-11-10 17:54
Thanks for the very detailed report.

I was able to reproduce the issue in VSCode, too. The problem does *not* originate from the parser, but from the completion itself. The parse tree looks fine to me. The parser inserts a closing brace before the `\emph` command. It looks like this:

```
ROOT@0..47
  PREAMBLE@0..47
    TEXT@0..9
      WORD@0..8 "Equation"
      WHITESPACE@8..9 " "
    LABEL_REFERENCE@9..24
      LABEL_REFERENCE_NAME@9..15 "\\eqref"
      CURLY_GROUP_WORD_LIST@15..24
        L_CURLY@15..16 "{"
        KEY@16..24
          WORD@16..18 "eq"
          WHITESPACE@18..19 " "
          WORD@19..21 "is"
          WHITESPACE@21..22 " "
          WORD@22..23 "a"
          WHITESPACE@23..24 " "
        MISSING@24..24 ""                        <-- The inserted closing brace
    GENERIC_COMMAND@24..38
      GENERIC_COMMAND_NAME@24..29 "\\emph"
      CURLY_GROUP@29..38
        L_CURLY@29..30 "{"
        TEXT@30..36
          WORD@30..36 "useful"
        R_CURLY@36..37 "}"
        WHITESPACE@37..38 " "
    TEXT@38..47
      WORD@38..47 "identity."
```

The problem stems from the completion. After gathering an initial list of the completion items (not the actual LSP type but much more lightweight), it calculates a score for each item. To do so, it determines the current text (pattern) at the cursor and compares each item to the text. The pattern in this case is "eq is a" so we do not get any fuzzy matches.
I think the solution is to use the words up to the cursor as the pattern and not the whole key.

I created the PR #511, which implements this behavior.

**Comment by clason** [comment] 2021-11-10 18:01
Yes, that sounds like a very reasonable solution. Thank you for looking at this so quickly!

**Closed** 2021-11-10 19:26 UTC
Labels: bug
