### ISSUE TITLE
No compile-errors reported in diagnostics

### ISSUE THREAD

**Issue by JoeyEremondi** [latex-lsp/texlab#339] opened 2020-12-30 19:21 UTC
Verison 2.20
OS: Ubuntu 20.04
Client: Emacs lsp-mode

### Input file:

```latex
\documentclass[12pt]{article}
\begi{document} %COMPILE ERROR
Hello world!
\end{document}
```

### Expected behaviour:

`publishDiagnostics` reports an error on line 2

### Observed behavior:

`publishDiagnostics` reports `[]`

Does texlab report compile errors? Or is this feature simply not supported yet?

**Comment by pfoerster** [comment] 2021-01-04 09:06
Thanks for the report. `texlab` should report compile errors by reading the log file. Where is the log file located (relative to the `tex` file)? Note that you need to trigger another request or notification for `texlab` to pick up the changes. This behavior will be fixed with the next version.

**Comment by mjlbach** [comment] 2021-01-07 11:21
Is there anything we should do client-side (at least, from my perspective, in neovim's language server client) to work around this in the meantime? What type of request/notification? textDidChange?

**Comment by clason** [comment] 2021-04-16 07:15
Is there anything I can help to fix that? I can reproduce this problem with neovim builtin LSP (and it apparently also happens on VS Code), but only in some situations.

For example, the following minimal file shows no diagnostics:
```tex
${$
```
(even after adding the typical document scaffolding), although the error appears in the log file:
[test.log](https://github.com/latex-lsp/texlab/files/6323202/test.log)

**Comment by pfoerster** [comment] 2021-04-19 18:21
Thanks for the example. This definetely helps a lot. It looks like the log parser is broken (again). Probably it will be best to port the log parser of [Overleaf](https://github.com/overleaf/latex-log-parser), which should function much better. Unfortunately, I am bit busy at the moment, but I am still actively working on texlab. However, I still need some time to finish the next version of texlab, which will fix this issue by using a proper file watching mechanism instead of polling.

**Comment by clason** [comment] 2021-04-19 18:31
If texlab 3.0 fixes the issue, that's of course fine with me as well :) And I completely understand real life taking precendence!

(But if there's a beta-level version of 3.0 I can already play with, that would make me happy ;))

**Closed** 2021-05-15 16:48 UTC
Labels: bug

**Comment by JoeyEremondi** [comment] 2021-05-15 18:04
Wow, thanks for all the hard work! Can't wait to try it out
