### ISSUE TITLE
chktex arguments

### ISSUE THREAD

**Issue by liuhaowen478** [latex-lsp/texlab#304] opened 2020-09-04 23:36 UTC
I'm trying to use a custom chktexrc file. It might be helpful if the server supports a configuration for passing arguments to chktex.

**Comment by pfoerster** [comment] 2020-09-08 07:04
This seems to be a duplicate of #309. You can track the progress, there. I am closing this one for now.

**Closed by pfoerster** 2020-09-08 07:04 UTC
Labels: duplicate
