### ISSUE TITLE
\includegraphics filename autocomplete does not work with optional arguments (emacs)

### ISSUE THREAD

**Issue by WannabeSmith** [latex-lsp/texlab#573] opened 2022-03-02 20:17 UTC
First, thanks for this awesome project!

**OS/editor details:**

OS: macOS Monterey
Editor: Emacs 27.2
LaTeX: TeX Live 2021 (installed mactex via homebrew)

**Description of the issue:**

When using the \includegraphics macro, if I write
```latex
\includegraphics{}
```
and begin typing a filename (e.g. an image) within the curly brackets, I successfully see an autocompleted list of filenames through which I can scroll, select, and so on. This is the desired behaviour.

However, if I add optional arguments, such as
```latex
\includegraphics[width=\textwidth]{}
```
and begin typing the same filename, no such autocompleted list appears. It would be great if the list of filenames were available regardless of whether optional arguments have been added or not.

**Comment by pfoerster** [comment] 2022-03-02 20:25
> It would be great if the list of filenames were available regardless of whether optional arguments have been added or not.

This should normally work so it appears to be a bug. On my machine, I cannot reproduce the issue with the example you provided:

![image](https://user-images.githubusercontent.com/13584622/156443404-ac7beadc-ade1-48a9-9798-a8a9e43b6015.png)

Is there something around the statement, which could mess with the parser like unbalanced braces? In this case, a full example file could help.
Also, what `texlab` version are you using?

**Comment by WannabeSmith** [comment] 2022-03-02 20:42
I am using texlab version 3.3.2.

You're absolutely right, the example I provided works fine. My apologies. It fails when I use the option `[width=0.5\textwidth]` (note the 0.5).

Here's an example. Note that the first two autocompletes work fine, while the third does not.

https://user-images.githubusercontent.com/5490890/156446040-a8ac55b0-9819-4fb9-b524-19dd2ac03c10.mov

**Comment by pfoerster** [comment] 2022-03-03 16:43
Thanks, I am able to reproduce the issue, now. 0edafcff34e467b66e18e6d1f5242c51c1c069e7 fixes the error in the parser.

**Comment by pfoerster** [comment] 2022-05-25 20:16
Released with `texlab 4.0.0`.

**Closed by pfoerster** 2022-05-25 20:16 UTC
Labels: bug
