### ISSUE TITLE
Support for multiple tex files?

### ISSUE THREAD

**Issue by TheZoq2** [latex-lsp/texlab#106] opened 2019-10-23 09:07 UTC
I hope I'm not missing something here, but as far as I can tell, texlive only
works in one file at a time. Most of my latex documents are split into separate
files, i.e.

```tex
% Setup
\begin{document}
    \input{src/introduction}
    \input{src/background}
    % ...
\end{document}
```

It would be great to have completion across these input files, and using the
packages defined in the main file. Is this possible right now, if not, how
difficult do you think it would be to support? I wouldn't mind trying to add
support for it if it's not too much effort.

**Comment by TheZoq2** [comment] 2019-10-23 09:23
I may have been a bit too quick at reporting this issue. From reading other issues, it looks like this should be supported, so clearly I'm missing something.

I use the language-client-neovim plugin, which simply invokes texlab as `texlab`. The main thing i'm interested in is completion, which does not seem to work across file.

My directory structure is as follows:

```
refs.bib
src/
  main.tex
  other_file.tex
```

**Comment by pfoerster** [comment] 2019-10-23 09:43
How do you include `other_file.tex`? Do you use `\input{src/other_file}`? If so, then this should be the cause of the issue. `TexLab` cannot reliably detect the directory you are compiling the document from 
(at least without additional input from the user) so we have to assume that all paths are relative to the current document. I am not sure if there is a good way to fix this issue because `vim` does not have the concept of a workspace folder.
For now, a workaround would involve including `other_file.tex` with `\input{other_file}` and compiling from the `src` directory.

**Comment by TheZoq2** [comment] 2019-10-23 09:52
Thanks for the quick reply, that's exactly how I include them, and it looks like moving the main file to the root folder of my projects also fixes the issue, as I would expect.

I also tried making a symlink to `src` in itself, but that didn't work.

Also, this might not be true for everyone, but I pretty much always run vim from the root directory of my project, so I would consider the working directory the workspace. Would it be possible to add a flag to texlive to use the working directory as the workspace?

**Comment by mklinik** [comment] 2020-02-21 10:27
I'm running into the same issue. My tex project is split up into multiple files, many of them are not valid tex documents on their own. In some of the files texlab auto completion works, in some it does not.

It would be nice to have documentation about how you have to set up a tex project so that texlab works reliable on any file.

I'm using vim on linux with vim-lsc.

**Comment by pfoerster** [comment] 2020-02-26 20:32
Can you try the latest master branch, please (don't mind the CI failure, it seems to be related to Rust nightly)? I added a new setting called `latex.rootDirectory`, which you have to set to the directory from which you call `latexmk`. This way, you can include files using `\include{src/other_file}` and keep your structure with the ``src` directory like @TheZoq2. Please let me know if this approach works for you. Sorry for the late answer.

**Comment by mklinik** [comment] 2020-02-27 06:39
Hey thanks, that sounds good. Where do I have to set this option? Does texlab have a config file? The documentation doesn't mention it as far as I can tell.

**Comment by pfoerster** [comment] 2020-02-27 08:15
Unfortunately, `vim-lsp` does not seem to support `workspace/configuration` or `workspace/didChangeWatchedConfiguration` yet. Nevertheless, I turned on the setting per default by using the current working directory as the default value. This should work fine for most cases but can be considered a breaking change for some use cases. That's why we have to bump the major version when releasing this change. 070d3829e6519c1276a73fadceba1b27f414df35 should fix the issue.

**Comment by clason** [comment] 2020-02-27 08:30
I do think `vim-lsp` supports `workspace/configuration`; I use it for
```viml
lsp#register_server({
                \ 'name': 'texlab',
                \ 'cmd': {server_info->[s:texlab]},
                \ 'config': {
                \ 'workspace_config': {'bibtex': {'formatting': {'lineLength': 0}}},
                \ })
```
(cut&paste, might be mismatched brackets).

There's no `didChangeWatchedConfiguration`, but there _is_ `didChangeConfiguration`-- is that sufficient?

**Comment by pfoerster** [comment] 2020-02-27 08:32
> There's no didChangeWatchedConfiguration, but there is didChangeConfiguration-- is that sufficient?

Yeah, that was a typo on my side. That should be sufficient now that TexLab supports push-based configuration.

**Comment by ywpkwon** [comment] 2020-03-16 21:59
Hi @pfoerster, I came from https://github.com/fannheyward/coc-texlab/issues/135. 
I investigated a bit more.
When a structure is like:
- ./main.tex
- test/cc.tex
I realized that building from `test/cc.tex` works with `\input{test/cc.tex}` but it doesn't work with `\subimport{test/}{cc.tex}` (using `\usepackage{import}`). Do you think `texlab` will handle this?

**Comment by pfoerster** [comment] 2020-03-17 07:50
Thanks for the report. I wasn't aware of this package when writing the include resolution algorithm but supporting `subimport` should not be too difficult. You can expect it with the next release of `texlab`.

**Comment by ywpkwon** [comment] 2020-03-18 00:53
@pfoerster, Thanks for the consideration. I forgot the detail, the `import` had a few advantages over `\input`, so I was using it (as far as I roughly remember, maybe some nested import in a subfolder or something...). For a minor issue, because of the grammar `\subimport{subfolder}{file}`, the file couldn't be auto-completed (so minor issue. I don't care about this issue, but just for information).

By the way, yesterday changed all `subimport` to `input`, and worked on child `.tex` files and also `.sty` or `.cls` files, and everything worked very well (w.r.t. recognizing the main tex file). It was really great. Thanks.

I can't wait until the next release! Good luck!

**Comment by Bno93** [comment] 2020-06-14 14:40
Hi all, 
I'm new to texlab and came across the same problem with mutliple tex files.
Currently I write on a large document with multiple `\input{}`'s. 
Here is a short description of my project structure:

```
project
- main.tex
| - topic1
| | - topic1.tex
| | - subtopic1.tex
| | - subtopic1.tex
... etc.
```

In the main file I use `\include{topic1/topic1}` and in the topic1.tex I use `\input{topic1/subtopic1.tex` to stick together my files. 
In all of my files I added `% !TeX root = ../main.tex` or `% !TeX root = ../../main.tex`

Now I read all the comments in this issue and set `"latex.rootDirectory": "${workspaceFolder}"` but when I'm try to run build on `subtopic1.tex` I ended up getting the error that ${workspaceFolder}/subtopic1.tex couldn't be found. 

BTW I'm using the texlab extension for vscode Version 2.2.0 with VSCode 1.46.0

**Comment by pfoerster** [comment] 2020-06-17 12:39
> In all of my files I added % !TeX root = ../main.tex or % !TeX root = ../../main.tex

You do not need to add these comments. TexLab ignores these comments and tries to figure out the dependency graph on its own.

> Now I read all the comments in this issue and set "latex.rootDirectory": "${workspaceFolder}" but when I'm try to run build on subtopic1.tex I ended up getting the error that ${workspaceFolder}/subtopic1.tex couldn't be found.

You can set `latex.rootDirectory` to either `"."` or the absolute path. The `${workspaceFolder}` is only supported by VSCode and it does not get expanded by VSCode when sending the configuration. Note that you need to use the "Open Folder" feature from VSCode if you want to use the relative path (so the working directory gets correctly set to the workspace folder).

Please let me know if this fixes the issue for you.

**Comment by Bno93** [comment] 2020-06-17 13:18
@pfoerster  Thanks for the answer. 
I added `latex.rootDirectory: "."` to my settings and now I'm able to build my document form all of my sub files.

Why don't you set the default value of `latex.rootDirectory` to `"."` to have a better out of the box experience or would this break things for single file use case ?

**Comment by pfoerster** [comment] 2020-06-17 14:19
> Why don't you set the default value of latex.rootDirectory to "." to have a better out of the box experience or would this break things for single file use case ?

This was once the default setting but it breaks building and analyzing projects that are not opened with the "Open Folder" feature from VSCode. In this case, "." would be relative to the home directory, which is generally not what you want.

**Comment by pfoerster** [comment] 2021-06-19 10:38
Closing this issue as it seems to be resolved. If the problem still persists, please open a new one.

**Closed by pfoerster** 2021-06-19 10:38 UTC
Labels: enhancement
