### ISSUE TITLE
Texlab compiles the wrong tex file and opens the wrong pdf

### ISSUE THREAD

**Issue by dpo** [latex-lsp/texlab#806] opened 2022-10-25 14:24 UTC
I found an odd behavior on macOS with Neovim (in fact, LunarVim), in the following situation:
* I'm editing a multi-file document (not multi folder) but this may not matter as I'm only editing the main file;
* the folder also contains a second (independent) TeX document that appears first alphabetically (which may or may not matter), but which I am NOT currently editing---this document is NOT open in any of the buffers in my editor;
* I initially run `latexmk -C` to clean up all auxiliary files (including all PDFs);
* I "save" the document I'm editing: Texlab compiles it and opens the PDF with Skim (I activated `buildOnSave`);
* I then make other changes to the document I'm editing, save again, and the OTHER document gets compiled and the OTHER document's PDF opens up in a new Skim window.

Here's my config:
```lua
    settings = {
      texlab = {
        rootDirectory = nil,
        build = {
          executable = 'latexmk',
          args = { '-shell-escape', '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f' },
          onSave = true,
          forwardSearchAfter = true,
        },
        auxDirectory = '.',
        forwardSearch = {
          executable = '/Applications/Skim.app/Contents/SharedSupport/displayline',
          args = { "-g", "-b", "%l", "%p", "%f" },
        },
        chktex = {
          onOpenAndSave = true,
          onEdit = false,
        },
        diagnosticsDelay = 300,
        latexFormatter = 'latexindent',
        latexindent = {
          ['local'] = nil, -- local is a reserved keyword
          modifyLineBreaks = false,
        },
        bibtexFormatter = 'texlab',
        formatterLineLength = 0,
      }
```

**Comment by dpo** [comment] 2022-10-25 16:18
This may be the same issue as in https://github.com/latex-lsp/texlab/issues/757. I'm not using `subfiles`. There is indeed a shared bib file between the two documents. It's a classic setup for me.

**Comment by t-wissmann** [comment] 2022-10-26 09:08
I have a similar issue, where I edit `main.tex` and `:TexlabBuild` compiles the wrong file `oldmain.tex` in the same folder (also with a shared `.bib` file). So in my case, the lexicographic order isn't the issue.

**Comment by pierreglaser** [comment] 2022-10-26 18:03
Hitting the same issue.

**Comment by pfoerster** [comment] 2022-11-01 10:48
Thanks for the report. This might look like a duplicate of #757. 

The main problem is that `texlab` is not very restrictive, when it considers links between documents in order to not miss any dependencies. That's why a shared file can suffice to make `texlab` throw them into the same project, which is not ideal. I am currently working on a fix, which includes a larger changeset (see https://github.com/latex-lsp/texlab/tree/salsa). It cleans up the algorithm which builds the dependency graph.

**Comment by RichardKraus** [comment] 2022-11-10 15:56
btw a workaround for this is making a symlink to the bib file like so `ln -s original.bib somedocumentspecificname.bib` and then using that link as bib resource.
at least that works for me

**Comment by pfoerster** [comment] 2022-11-22 20:46
I have a PR ready which hopefully fixes this issue (and some others): https://github.com/latex-lsp/texlab/pull/823
Can you try it out, please?

**Closed** 2022-12-29 19:05 UTC
Labels: bug
