### ISSUE TITLE
ignore single warnings/errors

### ISSUE THREAD

**Issue by endir** [latex-lsp/texlab#1131] opened 2024-05-23 19:23 UTC
It is useful sometimes to ignore single warnings. For example I would like to have labels for each section even if I do not cite the section. so for example I would like to ignore the warnings on those lines. E.g.

\section{test}
\label{test} % type: ignore

so even if I do not have sometime \label{test} I would not get unused label warning

**Comment by DasNaCl** [comment] 2024-06-06 08:04
Seems to be a duplicate of #1092

**Closed** 2024-10-07 08:15 UTC
