### ISSUE TITLE
Completion hangs in Emacs/lsp-latex

### ISSUE THREAD

**Issue by roblem** [latex-lsp/texlab#456] opened 2021-07-07 15:24 UTC
Originally filed at https://github.com/ROCKTAKEY/lsp-latex/issues/30 (but closed and opened here).

Using the latest version 3.2.0 of texlab [from here](https://github.com/latex-lsp/texlab/releases/tag/v3.2.0) on linux/Fedora 34 and the `lsp-latex` package for emacs 27.2.    

When I am working on a tex document completions work fine for awhile.  Sometimes it will work for 2 minutes and sometimes 10 minutes.  At some point, when I am tab completing, emacs hangs.  If I let it timeout, I get messages like this in the warnings buffer:
```
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eqr)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
```
where company is the the completion package I am using in emacs.

On a "real" tex file with tons of equations, references, etc., this seems to happen within 5 minutes.  I created a new tex document and as I added things to it, it finally happened but only after about 20 minutes.  

In emacs, I can restart the texlab server and it will work for awhile before it begins hanging again.

Here is a log file for my short test document.  The hang happened within 1 minute. I completed some itemize environments, created a section (with label), created an equation, and then it hangs when I tried to complete \cite.  There is no systematic link between the command it is trying to complete and when hangs occur (I have seen it hang on sections, begin, equations, etc).

[texlab.log](https://github.com/latex-lsp/texlab/files/6778375/texlab.log)

**Comment by pfoerster** [comment] 2021-07-07 16:00
Thanks for the report and the log file. I was not able to reproduce the problem using VSCode but I managed to find out an issue in the logs. The following happens:

1. Whenever you trigger a completion request (and some other requests like hover), `texlab` fetches the current configuration and handles the request in parallel.
2. However, the last configuration request does not get answered by Emacs. In line 2401, you can see that the request ```DEBUG - > {"jsonrpc":"2.0","id":149,"method":"workspace/configuration","params":{"items":[{"section":"texlab"}]}}``` never receives a response from Emacs. 
3. Unfortunately, this causes `texlab` to lock an internal mutex, which is then never released. Only the completion requires this mutex and thus it cannot complete. This causes all other completion requests to deadlock as well, which in turn causes the thread pool to be exhausted after some time, which causes `texlab` to hang completely.

I can prevent the mutex from being locked indefinitely by cloning the required data (in this case it is quite cheap performance-wise) but nevertheless we should look into it why Emacs does not always send a response to the configuration requests.
You can try out the latest commit on the master branch, which should delay the issue much longer.

**Comment by roblem** [comment] 2021-07-08 10:53
Thanks.  The latest master has been working for me for 5 hours straight with no apparent performance bottlenecks. 

Question, should I close this or leave open, since there are still issues with Emacs sending the response?  I am available to do some log capturing/whatever you need for getting to bottom of emacs issue.

**Comment by pfoerster** [comment] 2021-07-12 18:11
Thanks for trying it out 👍 .
I guess we can close this issue. There is not really much more I can do from the side of `texlab`. Probably this needs to reported to the LSP plugin of Emacs. I am not really familiar with Emacs so I am still unsure where the problem exactly lies.

**Closed** 2021-07-12 18:52 UTC

**Comment by d9d6ka** [comment] 2022-10-23 05:22
The problem with lsp-mode/texlab is again relevant in Emacs 28.2 (at least Windows build).
After autocompletion invocation emacs hangs for 20-30 seconds with the "timeout" error.
In Emacs 28.1 everything is ok!
